version: '3.8'
services:
  web:
    build:
      context: ./
    volumes:
      - .:/opt/app
    command: yarn dev
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: development
      DEBUG: nextjs-docker:*
